"""add_society_and_property_modules

Revision ID: 067dd28b623a
Revises: 3d99874fb2b5
Create Date: 2026-07-06 13:06:13.426644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067dd28b623a'
down_revision: Union[str, Sequence[str], None] = '3d99874fb2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('societies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('banner_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region', name='uq_society_name_region')
    )
    op.create_index(op.f('ix_societies_deleted_at'), 'societies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_societies_name'), 'societies', ['name'], unique=False)
    op.create_index(op.f('ix_societies_region'), 'societies', ['region'], unique=False)
    op.create_table('society_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_due_day', sa.Integer(), nullable=False),
    sa.Column('late_fee_percentage', sa.Float(), nullable=False),
    sa.Column('allow_visitor_auto_approve', sa.Boolean(), nullable=False),
    sa.Column('enable_gate_pass', sa.Boolean(), nullable=False),
    sa.Column('visitor_validation_required', sa.Boolean(), nullable=False),
    sa.Column('amenity_booking_advance_days', sa.Integer(), nullable=False),
    sa.Column('emergency_contact_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_society_settings_deleted_at'), 'society_settings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_society_settings_society_id'), 'society_settings', ['society_id'], unique=True)
    op.create_table('wings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'name', name='uq_wing_society_name')
    )
    op.create_index(op.f('ix_wings_deleted_at'), 'wings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_wings_society_id'), 'wings', ['society_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wing_id', sa.UUID(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wing_id', 'floor_number', name='uq_floor_wing_number')
    )
    op.create_index(op.f('ix_floors_deleted_at'), 'floors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_floors_wing_id'), 'floors', ['wing_id'], unique=False)
    op.create_table('flats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('wing_id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=False),
    sa.Column('flat_number', sa.String(length=50), nullable=False),
    sa.Column('flat_type', sa.String(length=50), nullable=False),
    sa.Column('flat_size', sa.Float(), nullable=False),
    sa.Column('occupancy_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'flat_number', name='uq_flat_society_number')
    )
    op.create_index(op.f('ix_flats_deleted_at'), 'flats', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_flats_floor_id'), 'flats', ['floor_id'], unique=False)
    op.create_index(op.f('ix_flats_society_id'), 'flats', ['society_id'], unique=False)
    op.create_index(op.f('ix_flats_wing_id'), 'flats', ['wing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flats_wing_id'), table_name='flats')
    op.drop_index(op.f('ix_flats_society_id'), table_name='flats')
    op.drop_index(op.f('ix_flats_floor_id'), table_name='flats')
    op.drop_index(op.f('ix_flats_deleted_at'), table_name='flats')
    op.drop_table('flats')
    op.drop_index(op.f('ix_floors_wing_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_deleted_at'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_wings_society_id'), table_name='wings')
    op.drop_index(op.f('ix_wings_deleted_at'), table_name='wings')
    op.drop_table('wings')
    op.drop_index(op.f('ix_society_settings_society_id'), table_name='society_settings')
    op.drop_index(op.f('ix_society_settings_deleted_at'), table_name='society_settings')
    op.drop_table('society_settings')
    op.drop_index(op.f('ix_societies_region'), table_name='societies')
    op.drop_index(op.f('ix_societies_name'), table_name='societies')
    op.drop_index(op.f('ix_societies_deleted_at'), table_name='societies')
    op.drop_table('societies')
    # ### end Alembic commands ###
