"""remove_email_verification

Revision ID: 2c677e29b7dc
Revises: cd45eba45920
Create Date: 2026-07-09 13:16:30.917487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c677e29b7dc'
down_revision: Union[str, Sequence[str], None] = 'cd45eba45920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vendor_ratings_user_id', table_name='vendor_ratings')
    op.drop_index('ix_vendor_ratings_vendor_id', table_name='vendor_ratings')
    op.drop_table('vendor_ratings')
    op.drop_index('ix_vendors_deleted_at', table_name='vendors')
    op.drop_index('ix_vendors_phone', table_name='vendors')
    op.drop_index('ix_vendors_society_id', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('ix_email_verifications_token_hash', table_name='email_verifications')
    op.drop_index('ix_email_verifications_user_id', table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_verifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='email_verifications_pkey')
    )
    op.create_index('ix_email_verifications_user_id', 'email_verifications', ['user_id'], unique=False)
    op.create_index('ix_email_verifications_token_hash', 'email_verifications', ['token_hash'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('society_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='vendors_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name='vendors_society_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='vendors_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='vendors_pkey'),
    sa.UniqueConstraint('society_id', 'phone', name='uq_vendor_society_phone'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_vendors_society_id', 'vendors', ['society_id'], unique=False)
    op.create_index('ix_vendors_phone', 'vendors', ['phone'], unique=False)
    op.create_index('ix_vendors_deleted_at', 'vendors', ['deleted_at'], unique=False)
    op.create_table('vendor_ratings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vendor_ratings_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='vendor_ratings_vendor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vendor_ratings_pkey')
    )
    op.create_index('ix_vendor_ratings_vendor_id', 'vendor_ratings', ['vendor_id'], unique=False)
    op.create_index('ix_vendor_ratings_user_id', 'vendor_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###
