"""add_society_join_code

Revision ID: 6290d2e80645
Revises: 2c677e29b7dc
Create Date: 2026-07-09 15:56:38.888322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6290d2e80645'
down_revision: Union[str, Sequence[str], None] = '2c677e29b7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('join_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_societies_join_code'), 'societies', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_societies_join_code'), table_name='societies')
    op.drop_column('societies', 'join_code')
    # ### end Alembic commands ###
