"""remove_vendor_and_treasurer

Revision ID: cd45eba45920
Revises: 72b65fcfc868
Create Date: 2026-07-07 20:08:48.641448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd45eba45920'
down_revision: Union[str, Sequence[str], None] = '72b65fcfc868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('complaints_vendor_id_fkey'), 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_vendor_id'), table_name='complaints')
    op.drop_column('complaints', 'vendor_id')
    op.drop_index(op.f('ix_vendor_ratings_user_id'), table_name='vendor_ratings')
    op.drop_index(op.f('ix_vendor_ratings_vendor_id'), table_name='vendor_ratings')
    op.drop_table('vendor_ratings')
    op.drop_index(op.f('ix_vendors_deleted_at'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_phone'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_society_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('vendor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('complaints_vendor_id_fkey'), 'complaints', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_complaints_vendor_id'), 'complaints', ['vendor_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('society_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('vendors_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('vendors_society_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('vendors_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('vendors_pkey')),
    sa.UniqueConstraint('society_id', 'phone', name=op.f('uq_vendor_society_phone'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vendors_society_id'), 'vendors', ['society_id'], unique=False)
    op.create_index(op.f('ix_vendors_phone'), 'vendors', ['phone'], unique=False)
    op.create_index(op.f('ix_vendors_deleted_at'), 'vendors', ['deleted_at'], unique=False)
    op.create_table('vendor_ratings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vendor_ratings_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('vendor_ratings_vendor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vendor_ratings_pkey'))
    )
    op.create_index(op.f('ix_vendor_ratings_vendor_id'), 'vendor_ratings', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_ratings_user_id'), 'vendor_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###
